# Generated by Django 4.2 on 2023-04-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("complement", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(max_length=8)),
            ],
            options={
                "db_table": "suppliers",
            },
        ),
    ]
