# Generated by Django 4.2 on 2023-04-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="complement",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="number",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(default=None, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="name",
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
