# Generated by Django 4.2 on 2023-04-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_address_of_delivery_order_supplier"),
        ("products", "0001_initial"),
        ("order_items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_order_product",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product")},
        ),
    ]
